
CREATE TABLE IF NOT EXISTS public."Users"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Title" text COLLATE pg_catalog."default",
    "FirstName" text COLLATE pg_catalog."default",
    "LastName" text COLLATE pg_catalog."default",
    "Email" text COLLATE pg_catalog."default",
    "Role" integer NOT NULL,
    "PasswordHash" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

INSERT INTO public."Users"(
	"Id", "Title", "FirstName", "LastName", "Email", "Role", "PasswordHash")
	VALUES (17, 'Mr', 'Chandra19', 'Muddam19', 'test19@test.com', 0, '$2a$11$Vw9ti0qfT5IwhIxACWg0a.LZBFK2CbUVWKqhykotORcnkWBoCNJzS');